### ISSUE TITLE
Modal Problem in relative boxes

### ISSUE THREAD

**Issue by Vahid-Taheri** [rzkhosroshahi/react-jalali-datepicker#15]
Hi,
In my idea , this issue caused by not following some standards on designing the DOM of modal.
You provided an absolute and flex modal in your component.
It should be appear at the end of body tag , as other overlays that provided by others(that i mentioned it a a standard).
It causes that your absolute overlay depends on body but with your design , it appears where it React tag inserts. If the parent of it would be a box(div or ...) with style "position : relative" it doesn't depend on body dimensions and relative box limits it.

As the summary , it's better that you make changes to make overlay DOM at the end of body to solve this problem.

With love and thanks a lot !

**Comment by rzkhosroshahi** [comment]
Hey @Vahid-Taheri 
Thanks, I'm sorry to delay :(
I'm too busy Vahid if you can solve this issue free to create a pull request

good luck

**Comment by mehdiraized** [comment]
hi
[this pull request](https://github.com/rzkhosroshahi/react-jalali-datepicker/pull/19)

**Comment by rzkhosroshahi** [comment]
https://github.com/rzkhosroshahi/react-jalali-datepicker/pull/19
