### ISSUE TITLE
Disable Time from DatePicker

### ISSUE THREAD

**Issue by theMasix** [rzkhosroshahi/react-jalali-datepicker#24]
Hello. Thanks for developing this awesome component.
But It's documentation and the capability to customize the functionality is BAD!
I want to disable the time from DatePicker component. How could I do that?

**Comment by rzkhosroshahi** [comment]
Hey thanks
I'm working on a new version of this package, but I don't know when it will be available.
anyway If you want to implement it, feel free to open a PR ☺️

**Comment by theMasix** [comment]
Added the Doc in bbac107e12fb2460426024286b40bac5cd07cc25 and renamed in 7ed6e69f41a20cd06c42f7fed2201eca85476bc4. Why I didn't see it?

**Comment by theMasix** [comment]
Fixed by #37
