### ISSUE TITLE
Using dayjs instead of moment.js

### ISSUE THREAD

**Issue by ZMashhadizadeh** [rzkhosroshahi/react-jalali-datepicker#32]
Hi,
As the moment team said, there is better alternatives for moment.js.
https://momentjs.com/docs/#/-project-status/

I replaced the moment.js with dayjs and you can review my pull request.

**Comment by ZMashhadizadeh** [comment]
@rzkhosroshahi

**Comment by rzkhosroshahi** [comment]
Hey @ZMashhadizadeh 
This pull request was merged and now it's available in the latest npm version.
thanks for contributing, it's really helpful 🙏.
