### ISSUE TITLE
Button that toggles the picker between picking date and picking time has no "type" property

### ISSUE THREAD

**Issue by iman700** [rzkhosroshahi/react-jalali-datepicker#36]
The button that toggles the date picker between date picking and time picking doesn't have type="button" property. By default, the browser submits the form containing the button on the event of clicking and this causes unwanted behavior. Add type="button" to the data and time picker toggle button to solve this problem. Thanks

**Comment by rzkhosroshahi** [comment]
This issue fixed and now available on the `1.2.1` version
