### ISSUE TITLE
timePicker={false} not working

### ISSUE THREAD

**Issue by aliasadolahi74** [rzkhosroshahi/react-jalali-datepicker#41]
Hi, I can't disable time from datepicker.

**Comment by rzkhosroshahi** [comment]
Hi @aliasadolahi74
 
It's duplicate #24.
this issue will resolve in the next version of the package

**Comment by mahyaa21** [comment]
Is it resolved?

**Comment by everythinginjs** [comment]
Hello @rzkhosroshahi, it is resolved?
